-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TFD105_G5
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TFD105_G5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TFD105_G5` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `TFD105_G5` ;

-- -----------------------------------------------------
-- Table `TFD105_G5`.`COMPANY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TFD105_G5`.`COMPANY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  `LASTNAME` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(20) NOT NULL,
  `OPEN` BIT(1) NOT NULL,
  `STATUS` CHAR(1) NOT NULL,
  `LOGINTIME` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TFD105_G5`.`EXPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TFD105_G5`.`EXPO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `START_TIME` DATE NOT NULL,
  `END_TIME` DATE NOT NULL,
  `OPEN` VARCHAR(12) NOT NULL,
  `MEETING_INTRO` TEXT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TFD105_G5`.`COMPANY_INFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TFD105_G5`.`COMPANY_INFO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ONBOARD` BIT(1) NOT NULL,
  `INTRODUCE` TEXT NULL,
  `LOGO` VARCHAR(100) NULL,
  `TYPE` VARCHAR(10) NULL,
  `ROBOT` VARCHAR(10) NULL,
  `VIDEO` VARCHAR(100) NULL,
  `MODIFY_DATE` DATETIME NOT NULL,
  `COMPANY_ID` INT NOT NULL,
  `EXPO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_COMPANY_INFO_COMPANY_ID_idx` (`COMPANY_ID` ASC) VISIBLE,
  INDEX `FK_COMPANY_INFO_EXPO_ID_idx` (`EXPO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_COMPANY_INFO_COMPANY_ID`
    FOREIGN KEY (`COMPANY_ID`)
    REFERENCES `TFD105_G5`.`COMPANY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMPANY_INFO_EXPO_ID`
    FOREIGN KEY (`EXPO_ID`)
    REFERENCES `TFD105_G5`.`EXPO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TFD105_G5`.`GUEST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TFD105_G5`.`GUEST` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `UNIT` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `MODIFY_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TFD105_G5`.`CONPANY_BOARD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TFD105_G5`.`CONPANY_BOARD` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `G_MSG` VARCHAR(200) NULL,
  `G_MSGTIME` DATETIME NULL,
  `C_MSG` VARCHAR(200) NULL,
  `C_MSGTIME` DATETIME NULL,
  `OPEN` BIT(1) NOT NULL,
  `COMPANY_INFO_ID` INT NULL,
  `GUEST_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_CONPANY_BOARD_GUEST_ID_idx` (`GUEST_ID` ASC) VISIBLE,
  INDEX `FK_CONPANY_BOARD_ COMPANY_INFO_ID_idx` (`COMPANY_INFO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_CONPANY_BOARD_ COMPANY_INFO_ID`
    FOREIGN KEY (`COMPANY_INFO_ID`)
    REFERENCES `TFD105_G5`.`COMPANY_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CONPANY_BOARD_GUEST_ID`
    FOREIGN KEY (`GUEST_ID`)
    REFERENCES `TFD105_G5`.`GUEST` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TFD105_G5`.`TECH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TFD105_G5`.`TECH` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `LINK` VARCHAR(200) NOT NULL,
  `STATUS` CHAR(1) NOT NULL,
  `COMPANY_INFO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_TECH_COMPANY_INFO_ID_idx` (`COMPANY_INFO_ID` ASC) VISIBLE,
  CONSTRAINT `FK_TECH_COMPANY_INFO_ID`
    FOREIGN KEY (`COMPANY_INFO_ID`)
    REFERENCES `TFD105_G5`.`COMPANY_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TFD105_G5`.`NEWS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TFD105_G5`.`NEWS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(60) NOT NULL,
  `CONTENT` TEXT NOT NULL,
  `PHOTO` VARCHAR(100) NOT NULL,
  `LINK` VARCHAR(100) NOT NULL,
  `TIME` DATE NOT NULL,
  `STATUS` CHAR(1) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TFD105_G5`.`CONTECT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TFD105_G5`.`CONTECT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `PHONE` VARCHAR(10) NOT NULL,
  `COMPANY` VARCHAR(100) NOT NULL,
  `TYPE` VARCHAR(50) NULL,
  `CONTENT` TEXT NULL,
  `REPLY_CNT` TEXT NULL,
  `STATUS` BIT(1) NOT NULL,
  `TIME` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TFD105_G5`.`AGENDA_TIME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TFD105_G5`.`AGENDA_TIME` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `START_TIME` TIME NOT NULL,
  `END_TIME` TIME NOT NULL,
  `STATUS` CHAR(1) NOT NULL,
  `OPEN` BIT(1) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TFD105_G5`.`AGENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TFD105_G5`.`AGENDA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATE` DATE NOT NULL,
  `START_TIME` TIME NOT NULL,
  `END_TIME` TIME NOT NULL,
  `THEME` VARCHAR(60) NOT NULL,
  `STATUS` CHAR(1) NOT NULL,
  `LINK` VARCHAR(100) NOT NULL,
  `NAME` VARCHAR(50) NULL,
  `PHOTO` VARCHAR(100) NULL,
  `INTRODUCE` TEXT NULL,
  `TIME` DATETIME NULL,
  `AGENDA_TIME_ID` INT NULL,
  `COMPANY_INFO_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_TECH_COMPANY_INFO_ID_idx` (`COMPANY_INFO_ID` ASC) VISIBLE,
  INDEX `FK_LIVE_LIST_AGENDA_TIME_ID_idx` (`AGENDA_TIME_ID` ASC) VISIBLE,
  CONSTRAINT `FK_AGENDA_COMPANY_INFO_ID`
    FOREIGN KEY (`COMPANY_INFO_ID`)
    REFERENCES `TFD105_G5`.`COMPANY_INFO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AGENDA_AGENDA_TIME_ID`
    FOREIGN KEY (`AGENDA_TIME_ID`)
    REFERENCES `TFD105_G5`.`AGENDA_TIME` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TFD105_G5`.`LIVE_BOARD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TFD105_G5`.`LIVE_BOARD` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CONTENT` VARCHAR(200) NOT NULL,
  `STATUS` CHAR(1) NOT NULL,
  `LIVE_LIST_ID` INT NOT NULL,
  `COMPANY_ID` INT NULL,
  `GUEST_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_LIVE_BOARD_COMPANY_ID_idx` (`COMPANY_ID` ASC) VISIBLE,
  INDEX `FK_LIVE_BOARD_GUEST_ID_idx` (`GUEST_ID` ASC) VISIBLE,
  CONSTRAINT `FK_LIVE_BOARD_COMPANY_ID`
    FOREIGN KEY (`COMPANY_ID`)
    REFERENCES `TFD105_G5`.`COMPANY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LIVE_BOARD_GUEST_ID`
    FOREIGN KEY (`GUEST_ID`)
    REFERENCES `TFD105_G5`.`GUEST` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
